import 'dart:async';

import 'package:flutter/material.dart';
import '../models/drink_type.dart';
import '../services/coach_service.dart';
import '../theme/app_theme.dart';
import 'soft_card.dart';

/// "Splash" — a little water-drop buddy that reacts to how hydrated you are
/// today. It changes face, colour and message as you sip toward your goal,
/// and bobs gently while it waits. The personality piece of HydroTracker.
///
/// Splash now *talks with an LLM*: its message is generated by the [CoachService]
/// (a Groq model behind a Supabase Edge Function) from the day's progress, time,
/// weather and streak — flagged with an "AI" badge so it's clear the buddy is AI
/// driven. It fetches once, then smart-refreshes after you log a drink (debounced
/// so a flurry of logs triggers one update). When the AI can't be reached it
/// quietly falls back to Splash's built-in, mood-based line, so the buddy always
/// has something to say.
class HydrationBuddy extends StatefulWidget {
  const HydrationBuddy({
    super.key,
    required this.currentMl,
    required this.targetMl,
    this.nudge,
    this.tempC,
    this.tempLabel,
    this.place,
    this.streak,
    this.mix,
    this.service = const CoachService(),
  });

  final int currentMl;
  final int targetMl;

  /// A gentle "drink some water" prompt when a less-hydrating drink is leading
  /// the day. Splash shows it unless the goal is already met, in which case the
  /// celebration wins.
  final HydrationNudge? nudge;

  /// Context passed to the AI so its message fits the moment.
  final int? tempC;
  final String? tempLabel;
  final String? place;
  final int? streak;

  /// Millilitres logged today per drink type (e.g. {Water: 800, Coffee: 600}),
  /// so the AI can comment on hydration *balance*, not just total volume.
  final Map<String, int>? mix;

  final CoachService service;

  @override
  State<HydrationBuddy> createState() => _HydrationBuddyState();
}

enum BuddyMood { parched, thirsty, happy, overjoyed }

/// The body colour Splash wears for each mood — it deepens from a pale, parched
/// blue up to a rich, full "water blue" as you sip toward your goal, so the
/// buddy literally looks more hydrated the fuller it gets.
Color buddyColorFor(BuddyMood mood) {
  switch (mood) {
    case BuddyMood.overjoyed:
      return const Color(0xFF1479C9); // full — deep ocean-water blue
    case BuddyMood.happy:
      return const Color(0xFF2E97DB); // clear water blue
    case BuddyMood.thirsty:
      return const Color(0xFF63B8E6); // light water blue
    case BuddyMood.parched:
      return const Color(0xFFAFD3E6); // pale, washed-out blue
  }
}

/// Just the painted mascot, with no card or animation around it. Reused by the
/// home buddy card and the goal-celebration moment.
class BuddyFace extends StatelessWidget {
  const BuddyFace({super.key, required this.mood, this.size = 72, this.color});

  final BuddyMood mood;
  final double size;
  final Color? color;

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: size,
      height: size,
      child: CustomPaint(
        painter: _BuddyPainter(mood: mood, color: color ?? buddyColorFor(mood)),
      ),
    );
  }
}

class _HydrationBuddyState extends State<HydrationBuddy>
    with SingleTickerProviderStateMixin {
  late final AnimationController _bob = AnimationController(
    vsync: this,
    duration: const Duration(milliseconds: 2200),
  )..repeat(reverse: true);

  CoachAdvice? _advice;
  bool _loading = true;

  /// Coalesces rapid intake changes (logging several drinks) into one refresh.
  Timer? _debounce;
  static const _debounceDelay = Duration(milliseconds: 1500);

  @override
  void initState() {
    super.initState();
    _loadAdvice();
  }

  @override
  void didUpdateWidget(HydrationBuddy oldWidget) {
    super.didUpdateWidget(oldWidget);
    // Smart refresh: re-ask the AI whenever *anything* that shapes the message
    // changes — intake, goal, the live weather, or the streak — after a short
    // debounce so a flurry of changes (e.g. logging a few drinks) collapses into
    // one update. There's no manual refresh; the buddy keeps itself current.
    if (widget.currentMl != oldWidget.currentMl ||
        widget.targetMl != oldWidget.targetMl ||
        widget.tempC != oldWidget.tempC ||
        widget.tempLabel != oldWidget.tempLabel ||
        widget.place != oldWidget.place ||
        widget.streak != oldWidget.streak) {
      _debounce?.cancel();
      _debounce = Timer(_debounceDelay, _loadAdvice);
    }
  }

  Future<void> _loadAdvice() async {
    _debounce?.cancel(); // a triggered load supersedes any pending one
    setState(() => _loading = true);
    final advice = await widget.service.fetch(
      intakeMl: widget.currentMl,
      goalMl: widget.targetMl,
      tempC: widget.tempC,
      tempLabel: widget.tempLabel,
      place: widget.place,
      streak: widget.streak,
      mix: widget.mix,
    );
    if (!mounted) return;
    setState(() {
      _advice = advice;
      _loading = false;
    });
  }

  /// True when Splash is showing a live, AI-generated line (not the offline
  /// fallback) — gates the "AI" badge so it's honest.
  bool get _isLiveAi => _advice != null && !_advice!.isFallback;

  @override
  void dispose() {
    _debounce?.cancel();
    _bob.dispose();
    super.dispose();
  }

  BuddyMood get _mood {
    final frac = widget.targetMl == 0
        ? 0.0
        : widget.currentMl / widget.targetMl;
    if (frac >= 1.0) return BuddyMood.overjoyed;
    if (frac >= 0.55) return BuddyMood.happy;
    if (frac >= 0.2) return BuddyMood.thirsty;
    return BuddyMood.parched;
  }

  ({String title, String line, Color color}) get _persona {
    final color = buddyColorFor(_mood);
    // A gentle nudge toward water when a less-hydrating drink is leading — but
    // only while the goal is still in reach. A smashed goal celebrates first.
    final nudge = widget.nudge;
    if (nudge != null && _mood != BuddyMood.overjoyed) {
      return (title: nudge.title, line: nudge.line, color: color);
    }
    switch (_mood) {
      case BuddyMood.overjoyed:
        return (
          title: 'Goal smashed! 🎉',
          line: "You're a Hydration Hero today. Splash is beaming!",
          color: color,
        );
      case BuddyMood.happy:
        return (
          title: 'Feeling fresh!',
          line: 'Over halfway there — keep the tide rolling.',
          color: color,
        );
      case BuddyMood.thirsty:
        return (
          title: 'Getting there…',
          line: 'A few more sips and Splash will be smiling.',
          color: color,
        );
      case BuddyMood.parched:
        return (
          title: "I'm parched!",
          line: 'Tap a quick log below to help Splash out.',
          color: color,
        );
    }
  }

  @override
  Widget build(BuildContext context) {
    final persona = _persona;
    // Splash speaks the AI line when it's live; otherwise its own mood line.
    final line = _isLiveAi ? _advice!.message : persona.line;
    return SoftCard(
      padding: const EdgeInsets.symmetric(horizontal: 18, vertical: 16),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          SizedBox(
            width: 72,
            height: 72,
            child: AnimatedBuilder(
              animation: _bob,
              builder: (context, child) {
                final dy = (0.5 - _bob.value) * 8; // gentle ±4px bob
                return Transform.translate(
                  offset: Offset(0, dy),
                  child: child,
                );
              },
              child: BuddyFace(mood: _mood, color: persona.color, size: 72),
            ),
          ),
          const SizedBox(width: 16),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              mainAxisSize: MainAxisSize.min,
              children: [
                Row(
                  children: [
                    Expanded(
                      child: Text(
                        persona.title,
                        maxLines: 1,
                        overflow: TextOverflow.ellipsis,
                        style: AppTheme.headlineLg.copyWith(fontSize: 17),
                      ),
                    ),
                    // ✨ AI badge pinned to the right — Splash is LLM-driven.
                    if (_isLiveAi) ...[
                      const SizedBox(width: 8),
                      _AiBadge(color: persona.color),
                    ],
                  ],
                ),
                const SizedBox(height: 4),
                AnimatedSwitcher(
                  duration: const Duration(milliseconds: 250),
                  child: _loading
                      ? const _BuddyLineLoading()
                      : Text(
                          line,
                          key: ValueKey(line),
                          style: AppTheme.bodyMd
                              .copyWith(fontSize: 13, height: 1.35),
                        ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

/// The little "AI" pill that marks Splash's message as LLM-generated.
class _AiBadge extends StatelessWidget {
  const _AiBadge({required this.color});

  final Color color;

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
      decoration: BoxDecoration(
        color: color.withValues(alpha: 0.14),
        borderRadius: BorderRadius.circular(20),
      ),
      child: Row(
        mainAxisSize: MainAxisSize.min,
        children: [
          Icon(Icons.auto_awesome_rounded, size: 11, color: color),
          const SizedBox(width: 3),
          Text(
            'AI',
            style: AppTheme.labelBold.copyWith(
              fontSize: 10,
              letterSpacing: 0.5,
              color: color,
            ),
          ),
        ],
      ),
    );
  }
}

/// A one-line shimmering placeholder shown while Splash's AI line is generating.
class _BuddyLineLoading extends StatelessWidget {
  const _BuddyLineLoading();

  @override
  Widget build(BuildContext context) {
    Widget bar(double widthFactor) => FractionallySizedBox(
          alignment: Alignment.centerLeft,
          widthFactor: widthFactor,
          child: Container(
            height: 10,
            decoration: BoxDecoration(
              color: AppColors.surfaceContainer,
              borderRadius: BorderRadius.circular(5),
            ),
          ),
        );

    return Column(
      key: const ValueKey('buddy-line-loading'),
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        bar(1),
        const SizedBox(height: 6),
        bar(0.55),
      ],
    );
  }
}

class _BuddyPainter extends CustomPainter {
  _BuddyPainter({required this.mood, required this.color});

  final BuddyMood mood;
  final Color color;

  @override
  void paint(Canvas canvas, Size size) {
    final s = size.shortestSide;
    final cx = size.width / 2;
    final r = s * 0.34;
    final cy = s * 0.58;

    // --- Body: a classic teardrop shape. ---
    final body = Path()
      ..moveTo(cx, s * 0.08)
      ..quadraticBezierTo(cx + r * 1.25, cy - r, cx + r, cy)
      ..arcToPoint(
        Offset(cx - r, cy),
        radius: Radius.circular(r),
        clockwise: true,
      )
      ..quadraticBezierTo(cx - r * 1.25, cy - r, cx, s * 0.08)
      ..close();

    canvas.drawPath(body, Paint()..color = color);

    // Soft highlight on the upper-left for a glossy look.
    canvas.drawCircle(
      Offset(cx - r * 0.4, cy - r * 0.45),
      r * 0.22,
      Paint()..color = Colors.white.withValues(alpha: 0.30),
    );

    // --- Eyes ---
    final eyeDx = r * 0.42;
    final eyeY = cy - r * 0.10;
    final eyeR = s * 0.075;
    final white = Paint()..color = Colors.white;
    final pupil = Paint()..color = AppColors.primary;

    for (final sign in [-1.0, 1.0]) {
      final ex = cx + sign * eyeDx;
      if (mood == BuddyMood.parched) {
        // Half-closed, weary eyes (downward arcs).
        final lid = Paint()
          ..color = AppColors.primary
          ..style = PaintingStyle.stroke
          ..strokeWidth = s * 0.03
          ..strokeCap = StrokeCap.round;
        canvas.drawArc(
          Rect.fromCircle(center: Offset(ex, eyeY), radius: eyeR),
          0.15,
          3.14 - 0.3,
          false,
          lid,
        );
      } else {
        canvas.drawCircle(Offset(ex, eyeY), eyeR, white);
        canvas.drawCircle(Offset(ex, eyeY + eyeR * 0.2), eyeR * 0.55, pupil);
        // Catchlight.
        canvas.drawCircle(
          Offset(ex - eyeR * 0.25, eyeY - eyeR * 0.2),
          eyeR * 0.18,
          white,
        );
      }
    }

    // --- Cheeks (blush) for the happy moods ---
    if (mood == BuddyMood.happy || mood == BuddyMood.overjoyed) {
      final blush = Paint()..color = AppColors.hibiscus.withValues(alpha: 0.35);
      for (final sign in [-1.0, 1.0]) {
        canvas.drawCircle(
          Offset(cx + sign * r * 0.62, eyeY + eyeR * 1.4),
          s * 0.05,
          blush,
        );
      }
    }

    // --- Mouth ---
    final mouthPaint = Paint()
      ..color = AppColors.primary
      ..style = PaintingStyle.stroke
      ..strokeWidth = s * 0.035
      ..strokeCap = StrokeCap.round;
    final mouthY = cy + r * 0.45;
    final mouthRect = Rect.fromCenter(
      center: Offset(cx, mouthY),
      width: r * 0.9,
      height: r * 0.7,
    );
    switch (mood) {
      case BuddyMood.overjoyed:
        // Big open smile.
        final smile = Paint()..color = AppColors.primary;
        final path = Path()
          ..addArc(
            Rect.fromCenter(
              center: Offset(cx, mouthY - r * 0.05),
              width: r * 0.95,
              height: r * 0.95,
            ),
            0.2,
            3.14 - 0.4,
          );
        canvas.drawPath(path, smile);
        break;
      case BuddyMood.happy:
        canvas.drawArc(mouthRect, 0.25, 3.14 - 0.5, false, mouthPaint);
        break;
      case BuddyMood.thirsty:
        // Small, hopeful smile.
        canvas.drawArc(
          Rect.fromCenter(
            center: Offset(cx, mouthY),
            width: r * 0.55,
            height: r * 0.4,
          ),
          0.4,
          3.14 - 0.8,
          false,
          mouthPaint,
        );
        break;
      case BuddyMood.parched:
        // Slight frown (flipped arc).
        canvas.drawArc(
          Rect.fromCenter(
            center: Offset(cx, mouthY + r * 0.2),
            width: r * 0.6,
            height: r * 0.45,
          ),
          3.14 + 0.4,
          3.14 - 0.8,
          false,
          mouthPaint,
        );
        break;
    }

    // --- Mood extras ---
    if (mood == BuddyMood.parched) {
      // A bead of sweat by the right eye.
      final sweat = Paint()..color = AppColors.turquoise;
      canvas.drawCircle(
        Offset(cx + eyeDx + eyeR * 1.2, eyeY - eyeR * 0.4),
        s * 0.035,
        sweat,
      );
    } else if (mood == BuddyMood.overjoyed) {
      // Little sparkles around the head.
      final spark = Paint()
        ..color = AppColors.hibiscus
        ..style = PaintingStyle.stroke
        ..strokeWidth = s * 0.025
        ..strokeCap = StrokeCap.round;
      void sparkle(double dx, double dy, double len) {
        final c = Offset(cx + dx, dy);
        canvas.drawLine(c.translate(-len, 0), c.translate(len, 0), spark);
        canvas.drawLine(c.translate(0, -len), c.translate(0, len), spark);
      }

      sparkle(-r * 1.25, s * 0.16, s * 0.05);
      sparkle(r * 1.2, s * 0.12, s * 0.06);
      sparkle(r * 0.95, s * 0.42, s * 0.04);
    }
  }

  @override
  bool shouldRepaint(_BuddyPainter old) =>
      old.mood != mood || old.color != color;
}
